<?php

namespace app\admin_api\controller;

use think\Controller;
use Firebase\JWT\JWT;

class Base extends Controller
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        header("Access-Control-Allow-Origin:*");
        header("Access-Control-Allow-Methods:*");
        header("Access-Control-Allow-Headers:*");
        header('Content-Type:application/json; charset=utf-8');

    }
}
