<?php

namespace app\api\controller;

use think\Controller;
use Firebase\JWT\JWT;

class Base extends Controller
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        header("Access-Control-Allow-Origin:*");
        header("Access-Control-Allow-Methods:*");
        header("Access-Control-Allow-Headers:*");
        header('Content-Type:application/json; charset=utf-8');
//        $key = "example_key";
//        $toke = array(
//            "iat" => time(),
//            "nbf" => time(),
//            'userinfo'=>[
//                'uid'=>1,
//                'name'=>'张三丰'
//            ]
//        );
//
//        $jwt = JWT::encode($toke, $key);
////        json(['code'=>1,'msg'=>$jwt])->send();//toke
//        $decoded = JWT::decode($jwt, $key, array('HS256'));
//        json(['code'=>0,'msg'=>$decoded])->send();//toke解密
    }
}
